# Generated by Django 5.1.7 on 2025-03-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive products won't be available for new orders",
            ),
        ),
    ]
