# Generated by Django 5.1.7 on 2025-03-28 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
        ("products", "0002_product_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loadingorderitem",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="loadingorderitem",
            unique_together={("loading_order", "product")},
        ),
        migrations.AddField(
            model_name="loadingorderitem",
            name="purchase_order_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loadingorderitem",
            name="return_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loadingorderitem",
            name="total_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="loadingorder",
            name="order_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="loadingorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Confirmed"),
                    ("loaded", "Loaded"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loadingorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.product"
            ),
        ),
        migrations.RemoveField(
            model_name="loadingorderitem",
            name="loaded_quantity",
        ),
        migrations.RemoveField(
            model_name="loadingorderitem",
            name="requested_quantity",
        ),
    ]
