# Generated by Django 5.1.7 on 2025-03-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_loadingorderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='local_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
