# Generated by Django 5.1.7 on 2025-04-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_deliveryorder_local_id_deliveryorder_sync_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="loadingorderitem",
            name="delivered_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loadingorderitem",
            name="loaded_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loadingorderitem",
            name="remaining_quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
