# Generated by Django 5.1.7 on 2025-04-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_deliveryorderitem_extra_quantity_publicsale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicsale",
            name="delivery_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="public_sales",
                to="delivery.deliveryteam",
            ),
        ),
        migrations.AlterField(
            model_name="returnedorder",
            name="return_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
