# Generated by Django 5.1.7 on 2025-04-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0007_alter_returnedorder_delivery_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryorder",
            name="delivery_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
