# Generated by Django 5.1.7 on 2025-04-20 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_remove_deliveryorder_unique_lo_route_seller_delivery_date_and_more'),
        ('seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='actual_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicsale',
            name='local_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publicsale',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Actually delivered quantity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='extra_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional quantity beyond ordered quantity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryorderitem',
            name='ordered_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity from sales order', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='publicsale',
            index=models.Index(fields=['route', 'sale_date'], name='delivery_pu_route_i_6957e9_idx'),
        ),
        migrations.AddIndex(
            model_name='publicsale',
            index=models.Index(fields=['sync_status'], name='delivery_pu_sync_st_e1f556_idx'),
        ),
    ]
