# Generated by Django 5.1.7 on 2025-04-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0011_deliveryorder_actual_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicsale",
            name="customer_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicsale",
            name="customer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publicsale",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="publicsale",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
