# Generated by Django 5.1.7 on 2025-04-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0012_alter_publicsale_customer_address_and_more"),
        ("sales", "0003_salesorder_unique_seller_delivery_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryorder",
            name="sales_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_orders",
                to="sales.salesorder",
            ),
        ),
    ]
