# Generated by Django 5.1.7 on 2025-04-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0013_alter_deliveryorder_sales_order"),
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashdenomination",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashdenomination",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_denominations",
                to="seller.route",
            ),
        ),
        migrations.AlterField(
            model_name="cashdenomination",
            name="delivery_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_denominations",
                to="delivery.deliveryorder",
            ),
        ),
    ]
