# Generated by Django 5.1.7 on 2025-04-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0014_cashdenomination_delivery_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deliveryorder",
            name="unique_lo_route_seller_delivery_date",
        ),
    ]
