# Generated by Django 5.1.7 on 2025-04-20 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0015_remove_deliveryorder_unique_lo_route_seller_delivery_date"),
        ("sales", "0003_salesorder_unique_seller_delivery_date"),
        ("seller", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="deliveryorder",
            constraint=models.UniqueConstraint(
                fields=("route", "seller", "delivery_date"),
                name="unique_lo_route_seller_delivery_date",
            ),
        ),
    ]
