# Generated by Django 5.1.7 on 2025-04-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0016_deliveryorder_unique_lo_route_seller_delivery_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deliveryorder",
            name="unique_lo_route_seller_delivery_date",
        ),
    ]
