# Generated by Django 5.1.7 on 2025-05-23 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0019_brokenorder_local_id_brokenorder_status_and_more"),
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryexpense",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_expenses",
                to="seller.route",
            ),
        ),
    ]
