# Generated by Django 5.1.7 on 2025-05-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0020_deliveryexpense_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicsale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("credit", "Credit"),
                    ("bank_transfer", "Bank Transfer"),
                    ("online", "Online"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
