# Generated by Django 5.1.7 on 2025-05-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0021_alter_publicsale_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryexpense",
            name="expense_type",
            field=models.CharField(
                choices=[
                    ("food", "Food/Snacks"),
                    ("vehicle", "Vehicle Repair/Maintenance"),
                    ("fuel", "Fuel"),
                    ("other", "Other Expenses"),
                    ("allowance", "Daily Allowance"),
                ],
                max_length=20,
            ),
        ),
    ]
