# Generated by Django 5.1.7 on 2025-05-30 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_alter_deliveryexpense_expense_type'),
        ('seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('local_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_locations_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='delivery.deliveryorder')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_locations', to='seller.route')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_locations', to='seller.seller')),
            ],
            options={
                'verbose_name': 'Delivery Location',
                'verbose_name_plural': 'Delivery Locations',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['seller', 'route', 'timestamp'], name='delivery_de_seller__5703cd_idx')],
            },
        ),
    ]
