# Generated by Django 5.1.7 on 2025-03-21 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
        ("seller", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellercalllog",
            name="sales_order",
        ),
        migrations.RemoveField(
            model_name="sellercalllog",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="sellercalllog",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="sellercalllog",
            name="next_call_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sellercalllog",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sellercalllog",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="seller.seller"
            ),
        ),
        migrations.AlterField(
            model_name="sellercalllog",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("no_answer", "No Answer"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
